name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      # setup dotnet based on global.json
      - uses: actions/setup-dotnet@v3.0.2
      # run the CI build
      - name: make ci
        run: make ci
      # run the CD build (on main only)
      - name: make cd
        if: github.ref == 'refs/heads/main'
        run: make cd
        env:
          NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
      - name: publish test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            TryOutPeekAtChangelog/TestResults/tests.trx